account/urls.py
from django.urls import path
from account.views import login_view, logout_view, account_view, reg_view, post_new, ProductsDetailView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from account.models import Post
from account import views
app_name = 'account'

urlpatterns = [
    path('reg/', reg_view, name='reg'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('add/', post_new, name='add'),
    path('', account_view, name='home'),
    path('account/<pk>/', ProductsDetailView.as_view(model=Post), name="Product_single"),
    path('edit/<int:id>/', views.edit),
    path('delete/<int:id>/', views.delete),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='home')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User,verbose_name='Студент', on_delete=models.CASCADE)
    qr = models.ImageField(upload_to='qr')
    text = models.TextField(max_length=10000)
    textqr = models.TextField(max_length=1000, default='qr')
    textot = models.TextField(max_length=1000, default='еще не ответили')
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(auto_now=True)
    YES = 'РЕШЕНО'
    NO = 'В ОЖИДАНИИ ОТВЕТА'
    YEAR_IN_SCHOOL_CHOICES = [
        (YES, 'РЕШЕНО'),
        (NO, 'В ОЖИДАНИИ ОТВЕТА'),
    ]
    year_in_school = models.CharField(
        max_length=200,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=NO,
    )
    def get_absolute_url(self):
        return reverse("account:Product_single", kwargs={'pk': self.pk})

    def __str__(self):
        return self.text

account/forms.py
from django import forms

from account.models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text','qr')

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from account.forms import PostForm
from django.utils import timezone
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from account.models import Post
from pathlib import Path
import cv2
import pathlib
BASE_DIR = Path(__file__).resolve().parent.parent
# Create your views here.
def logout_view(request):
    logout(request)
    return redirect('/')

def reg_view(request):

    if request.method == 'POST':
        
        form = UserCreationForm(request.POST)
        if form.is_valid():
            print(request.POST)
            form.save()
            
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            login_user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            if login_user:
                login(request, login_user)
                return redirect('/')
 
    
    else:
    
        form = UserCreationForm()
    

    return render(request, 'accounts/reg.html', {'form': form})

def login_view(request):

    if request.method == 'POST':
        
        form = request.POST
       
            
        
      
        password = form.get('password1')
        login_user = authenticate(username=form['username'], password=form['password1'])
        if login_user is not None:
            login(request, login_user)
            return redirect('/')
        
    else:
        print(request.POST)
        form = UserCreationForm()
    

    return render(request, 'accounts/login.html', {'form': form})



@login_required(login_url='/login/')
def account_view(request): 
    

    if request.user.groups.filter(name='manager').exists():
        context = {
        'posts': Post.objects.filter()
        }
        template = 'account_role.html'
    # иначе все остальные (обычные пользователи)
    else:
        context = {
        'posts': Post.objects.filter(author=request.user)
        }
       
        template = 'account.html'

    # сортировка выдачи заказов в обратном порядке (от последнего к первому)    

    return render(request, template, context)

@login_required(login_url='/login/')
def post_new(request):

    context = {}
    context['form'] = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        
        

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.qt = form.cleaned_data['qr']
                     
   
            post.created_date = timezone.now()
            post.save()
            print(post.qr.path, pathlib.Path(__file__).parent.absolute())
            qwee = post.qr.path

            imagess = cv2.imread(qwee)
            
            detector = cv2.QRCodeDetector()

            data, bbox, _ = detector.detectAndDecode(imagess)


            if bbox is not None:
                text_qr = data    
            else:
                text_qr = 'не смог прочитать qr-код с изображения'
            post.textqr = text_qr
            post.save()
            return redirect('/')
    else:
        form = PostForm()
        form.author = request.user
    return render(request, 'add.html', context)



class ProductsDetailView(DetailView):
    model = Post()
    template_name = 'zapros.html'



# изменение данных в бд
def edit(request, id):
    try:
        post = Post.objects.get(id=id)
 
        if request.method == "POST":
            post.textot = request.POST.get("textot")
            post.year_in_school = request.POST.get("year_in_school")
            print(post)
            post.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "edit.html", {"post": post})
    except Post.DoesNotExist:
        return HttpResponseNotFound("<h2>post not found</h2>")
     
# удаление данных из бд
def delete(request, id):
    try:
        post = post.objects.get(id=id)
        post.delete()
        return HttpResponseRedirect("/")
    except post.DoesNotExist:
        return HttpResponseNotFound("<h2>post not found</h2>")

templates/account.html
{% extends "base.html" %}


{% block title %}
login
{% endblock title %}

{% block content %}
<div class="col-lg-8 mx-auto p-3 py-md-5">
<main>
  <h1>{{ user.groups.all.0 }}</h1>
      {% if user.groups.all.0.name == 'manager' %}
      <h1>YES</h1>
      {% else %}
      <h1>Студент</h1>
      {% endif %}  
  <p class="fs-5 col-md-8">Отправить QR код и сообщение о проблеме на сайт!</p>

  <div class="mb-5">
    <a href="add" class="btn btn-primary btn-lg px-4">Отправить</a>
  </div>

  <hr class="col-3 col-md-2 mb-5">
  <div class="row g-5">
  {% for post in posts %}
  
    <div class="col-md-6">
    <h2>Запрос номер {{ post.id }}</h2>
    <p>Статус запроса - {{post.year_in_school}}</p>
    <p>Дата отправки - {{ post.created_date }}</p>
    <ul class="icon-list">
      <li><a href="{{ post.get_absolute_url }}" rel="noopener" target="_blank">Просмотр</a></li>

    </ul>
  </div>
    
{% endfor %}  
  </div>
</main>
</div>

{% endblock content %}

templates/account_role.html
{% extends "base.html" %}


{% block title %}
login
{% endblock title %}

{% block content %}
<div class="col-lg-8 mx-auto p-3 py-md-5">
<main>
  <h1>{{ user.groups.all.0 }}</h1>
      {% if user.groups.all.0.name == 'manager' %}

      {% else %}
      <h1>Студент</h1>
      {% endif %}  
  <p class="fs-5 col-md-8">тут вы можете редактировать и отвечать на запросы студентов!</p>

  

  <hr class="col-3 col-md-2 mb-5">
  <div class="row g-5">
  {% for post in posts %}
  
    <div class="col-md-6">
    <h2>Запрос номер {{ post.id }}</h2>
    <p>кто отправил запрос - {{post.author}}</p>
    <p>Статус запроса - {{post.year_in_school}}</p>
    <p>Дата отправки - {{ post.created_date }}</p>
    <ul class="icon-list">
      <li><a href="edit/{{ post.id }}" rel="noopener" target="_blank">Изменить и ответить студенту</a></li>

    </ul>
  </div>
    
{% endfor %}  
  </div>
</main>
</div>

{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<main class="form-signin">
    <div class="p-3 mb-3 bg-warning text-dark">{{ form.errors }}</div>
    
    <form action="" method="POST">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Вход</h1>
        <div class="form-floating">
                <label for="exampleInputEmail1">Логин</label>
                <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter username" required>
              </div>
              <div class="form-floating">
                <label for="exampleInputPassword1">Пароль</label>
                <input type="password" class="form-control" name="password1" id="exampleInputPassword1" placeholder="Password" required>
          
              
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
</main>
{% endblock %}

templates/accounts/reg.html
{% extends 'base.html' %}
{% block content %}
<main class="form-signin">
    <div class="p-3 mb-3 bg-warning text-dark">{{ form.errors }}</div>
    
    <form action="" method="POST">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">регистрация</h1>
        <div class="form-floating">
                <label for="exampleInputEmail1">Логин</label>
                <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter username" required>
              </div>
              <div class="form-floating">
                <label for="exampleInputPassword1">Пароль</label>
                <input type="password" class="form-control" name="password1" id="exampleInputPassword1" placeholder="Password" required>
              </div>
                 <div class="form-floating">
                <label for="exampleInputPassword1">Повторить пароль</label>
                <input type="password" class="form-control" name="password2" id="exampleInputPassword1" placeholder="confirm password" required>
              </div>
              
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
</main>
{% endblock %}

templates/add.html
{% extends 'base.html' %}

{% block content %}
<div class="col-lg-8 mx-auto p-3 py-md-5">
    <h1>Тут вы можете отправить запрос на сайт</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit" class="w-50 btn btn-primary btn-lg">Отправить</button>
    </form></div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- Dropzone js -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      </style>
    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Report app | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
  
        {% block content %}
        {% endblock content %}

        
    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
  </body>
</html>

templates/edit.html
{% extends "base.html" %}


{% block title %}
login
{% endblock title %}

{% block content %}
<div class="col-lg-8 mx-auto p-3 py-md-5">
<main>
  <h1>Кто отправил запрос - {{ post.author }}</h1>
      
      <img src="{{ post.qr.url }}" class="img-thumbnail" alt="...">
      
  <p class="fs-5 col-md-8">{{ post.text }}</p>
  <p class="fs-5 col-md-8">QR код - {{ post.textqr }}</p>
  <p class="fs-5 col-md-8">Статус - {{ post.year_in_school }}</p>
  <p class="fs-5 col-md-8">Дата отправки - {{ post.created_date }}</p>


  <hr class="col-3 col-md-2 mb-5">
  <h2>Ответить на обращение</h2>
  <div class="row g-5">
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="col-7">
            <label for="address" class="form-label">Ответить на обращение</label>
            <input type="text" class="form-control" id="address" name='textot' required="">
            
          </div>
          <br>
          <div class="col-md-5">
            <label for="country" class="form-label">Изменить статус обращения</label>
            <select class="form-select" id="country" required="" name='year_in_school'>
              <option value="">В ОЖИДАНИИ ОТВЕТА</option>
              <option>РЕШЕНО</option>
            </select>
            
            <br>
          </div>
        <button type="submit" class="w-50 btn btn-primary btn-lg">Ответить</button>
    </form></div>
  </div>
</main>
</div>

{% endblock content %}

templates/navbar.html
{% load static %}
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      
      
      {% if request.user.is_authenticated %}
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'account:home' %}" class="nav-link px-2 link-secondary">Профиль</a></li>
      </ul>
        <div class="nav-item dropdown">
          <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{request.user.profile.avatar.url}}" class="avatar-sm">&nbsp;{{request.user}}
          </div>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Выход</a></li>
          </ul>
        </div>
        {% else %}
        <div class="col-md-4 text-end">
            <a href="{% url 'account:login' %}"><button type="button" class="btn btn-outline-primary me-2">Войти</button></a>
     
            <a href="{% url 'account:reg' %}"><button type="button" class="btn btn-primary" >Регистрация</button></a>
          </div>
        {% endif %}
    </header>
  </div>

templates/zapros.html
{% extends "base.html" %}


{% block title %}
login
{% endblock title %}

{% block content %}
<div class="col-lg-8 mx-auto p-3 py-md-5">
<main>
  <h1>Кто отправил запрос - {{ post.author }}</h1>
      
      <img src="{{ post.qr.url }}" class="img-thumbnail" alt="...">
      
  <p class="fs-5 col-md-8">{{ post.text }}</p>
  <p class="fs-5 col-md-8">QR код - {{ post.textqr }}</p>
  <p class="fs-5 col-md-8">Статус - {{ post.year_in_school }}</p>
  <p class="fs-5 col-md-8">Дата отправки - {{ post.created_date }}</p>


  <hr class="col-3 col-md-2 mb-5">
  <div class="row g-5">
    <div class="col-md-6">
        <h2>Ответ на обращение</h2>
        <p>{{ post.textot}}.</p>
        
      </div>
  </div>
</main>
</div>

{% endblock content %}